"""add_storage_state

Revision ID: 36d74c0a988b
Revises: 2ebd38494b2c
Create Date: 2024-12-24 01:04:31.001012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '36d74c0a988b'
down_revision = '2ebd38494b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('cipher_state_storage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'cipher_state_storage')
    # ### end Alembic commands ###
