"""refactor_permission

Revision ID: 596cb7cbb087
Revises: 65d5397ec7cf
Create Date: 2024-07-27 20:53:50.298130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '596cb7cbb087'
down_revision = '65d5397ec7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('agent_user_uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('agent_unit_uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('agent_unit_node_uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('resource_repo_uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('resource_unit_uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('resource_unit_node_uuid', sa.UUID(), nullable=True))
    op.drop_index('ix_permissions_agent_uuid', table_name='permissions')
    op.drop_index('ix_permissions_resource_uuid', table_name='permissions')
    op.create_foreign_key(None, 'permissions', 'users', ['agent_user_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'units_nodes', ['agent_unit_node_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'units', ['resource_unit_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'units_nodes', ['resource_unit_node_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'units', ['agent_unit_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'repos', ['resource_repo_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('permissions', 'resource_uuid')
    op.drop_column('permissions', 'agent_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('agent_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('resource_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.create_index('ix_permissions_resource_uuid', 'permissions', ['resource_uuid'], unique=False)
    op.create_index('ix_permissions_agent_uuid', 'permissions', ['agent_uuid'], unique=False)
    op.drop_column('permissions', 'resource_unit_node_uuid')
    op.drop_column('permissions', 'resource_unit_uuid')
    op.drop_column('permissions', 'resource_repo_uuid')
    op.drop_column('permissions', 'agent_unit_node_uuid')
    op.drop_column('permissions', 'agent_unit_uuid')
    op.drop_column('permissions', 'agent_user_uuid')
    # ### end Alembic commands ###
