"""add_update_state

Revision ID: 2ebd38494b2c
Revises: f7530b7880cc
Create Date: 2024-12-21 10:41:01.747290

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "2ebd38494b2c"
down_revision = "f7530b7880cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column(
            "firmware_update_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "firmware_update_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column("last_firmware_update_datetime", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "last_firmware_update_datetime")
    op.drop_column("units", "firmware_update_error")
    op.drop_column("units", "firmware_update_status")
    # ### end Alembic commands ###
