"""add_unit_fld

Revision ID: ec67a994a505
Revises: 93b4283135ae
Create Date: 2024-05-07 03:48:13.172904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ec67a994a505'
down_revision = '93b4283135ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('current_commit_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'current_commit_version')
    # ### end Alembic commands ###
