"""del_update_freq

Revision ID: f0a9fd3812ec
Revises: 56e0d4eca5b9
Create Date: 2024-07-28 03:59:50.676038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f0a9fd3812ec'
down_revision = '56e0d4eca5b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'update_frequency_in_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('update_frequency_in_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
