"""del_code

Revision ID: e1b5afc3adfc
Revises: 7aa0ae7ba8c5
Create Date: 2024-05-11 17:14:36.720423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1b5afc3adfc'
down_revision = '7aa0ae7ba8c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_verification_code_key', 'users', type_='unique')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_verification_code_key', 'users', ['verification_code'])
    # ### end Alembic commands ###
