"""repo_autoupdate_add_commit

Revision ID: 38a938ad90f8
Revises: e1b5afc3adfc
Create Date: 2024-06-17 02:50:31.463735

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '38a938ad90f8'
down_revision = 'e1b5afc3adfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('default_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'default_commit')
    # ### end Alembic commands ###
