"""add_unit_node_creator

Revision ID: a45e1c0df0d3
Revises: 7e8f41d35420
Create Date: 2024-07-14 19:41:13.273966

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a45e1c0df0d3'
down_revision = '7e8f41d35420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units_nodes', sa.Column('creator_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'units_nodes', 'users', ['creator_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units_nodes', type_='foreignkey')
    op.drop_column('units_nodes', 'creator_uuid')
    # ### end Alembic commands ###
