"""add_edge_creator

Revision ID: 56e0d4eca5b9
Revises: 596cb7cbb087
Create Date: 2024-07-28 03:44:04.139117

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56e0d4eca5b9"
down_revision = "596cb7cbb087"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units_nodes_edges", sa.Column("creator_uuid", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "units_nodes_edges",
        "users",
        ["creator_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "units_nodes_edges", type_="foreignkey")
    op.drop_column("units_nodes_edges", "creator_uuid")
    # ### end Alembic commands ###
