"""add_repo_fld

Revision ID: 93b4283135ae
Revises: 8e84c4f4d99a
Create Date: 2024-05-07 02:14:29.537437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '93b4283135ae'
down_revision = '8e84c4f4d99a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('is_only_tag_update', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'is_only_tag_update')
    # ### end Alembic commands ###
