"""add_compilable

Revision ID: f7530b7880cc
Revises: f0a9fd3812ec
Create Date: 2024-12-10 13:03:59.021017

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'f7530b7880cc'
down_revision = 'f0a9fd3812ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Gitlab'))
    op.add_column('repos', sa.Column('is_compilable_repo', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('repos', sa.Column('releases_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('units', sa.Column('target_firmware_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default='null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'target_firmware_platform')
    op.drop_column('repos', 'releases_data')
    op.drop_column('repos', 'is_compilable_repo')
    op.drop_column('repos', 'platform')
    # ### end Alembic commands ###
