"""permission_edge

Revision ID: 7e8f41d35420
Revises: 38a938ad90f8
Create Date: 2024-07-12 23:12:44.179327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7e8f41d35420'
down_revision = '38a938ad90f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units_nodes_edges',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('node_output_uuid', sa.UUID(), nullable=True),
    sa.Column('node_input_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['node_input_uuid'], ['units_nodes.uuid'], ),
    sa.ForeignKeyConstraint(['node_output_uuid'], ['units_nodes.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_units_nodes_edges_uuid'), 'units_nodes_edges', ['uuid'], unique=False)
    op.add_column('permissions', sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('permissions', sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'resource_type')
    op.drop_column('permissions', 'agent_type')
    op.drop_index(op.f('ix_units_nodes_edges_uuid'), table_name='units_nodes_edges')
    op.drop_table('units_nodes_edges')
    # ### end Alembic commands ###
