"""add_permission

Revision ID: 5279f6e19c5c
Revises: ec67a994a505
Create Date: 2024-05-10 01:35:58.694114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5279f6e19c5c'
down_revision = 'ec67a994a505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('agent_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('resource_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_permissions_agent_uuid'), 'permissions', ['agent_uuid'], unique=False)
    op.create_index(op.f('ix_permissions_resource_uuid'), 'permissions', ['resource_uuid'], unique=False)
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource_uuid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_agent_uuid'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
