"""add_del_cascade

Revision ID: c235784f8b05
Revises: a45e1c0df0d3
Create Date: 2024-07-15 19:41:04.360995

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c235784f8b05'
down_revision = 'a45e1c0df0d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('units_nodes_edges_node_input_uuid_fkey', 'units_nodes_edges', type_='foreignkey')
    op.create_foreign_key(None, 'units_nodes_edges', 'units_nodes', ['node_input_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units_nodes_edges', type_='foreignkey')
    op.create_foreign_key('units_nodes_edges_node_input_uuid_fkey', 'units_nodes_edges', 'units_nodes', ['node_input_uuid'], ['uuid'])
    # ### end Alembic commands ###
