"""repo_clear

Revision ID: 934f56855401
Revises: 4a0d3bc6e94a
Create Date: 2025-07-09 13:11:55.627316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '934f56855401'
down_revision = '4a0d3bc6e94a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'cipher_credentials_private_repository')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('cipher_credentials_private_repository', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
