"""creds_for_registry

Revision ID: 4a0d3bc6e94a
Revises: b4648160f78e
Create Date: 2025-07-05 15:33:56.160129

"""
import json

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.orm import Session

from app.utils.utils import aes_gcm_decode, aes_gcm_encode

# revision identifiers, used by Alembic.
revision = '4a0d3bc6e94a'
down_revision = 'b4648160f78e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_registry', sa.Column('cipher_credentials_private_repository', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)

    repos = session.execute(sa.text(f"SELECT uuid, cipher_credentials_private_repository, creator_uuid, repository_registry_uuid FROM repos where cipher_credentials_private_repository is not null")).fetchall()

    if len(repos) > 0:

        registry_credentials = {}
        for uuid, cipher_credentials_private_repository, creator_uuid, repository_registry_uuid in repos:

            current_credentials = json.loads(aes_gcm_decode(cipher_credentials_private_repository))

            if str(repository_registry_uuid) not in registry_credentials:
                registry_credentials[str(repository_registry_uuid)] = {}

            if str(creator_uuid) not in registry_credentials[str(repository_registry_uuid)]:
                registry_credentials[str(repository_registry_uuid)][str(creator_uuid)] = {
                    "credentials": current_credentials,
                    "status": "NotVerified"
                }

        for repository_registry_uuid, struct in registry_credentials.items():
            new_cipher = aes_gcm_encode(json.dumps(struct))
            session.execute(
                sa.text(f"UPDATE repository_registry SET cipher_credentials_private_repository = '{new_cipher}' WHERE uuid = '{str(repository_registry_uuid)}'")
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_registry', 'cipher_credentials_private_repository')
    # ### end Alembic commands ###
