"""del_unit_node_agent

Revision ID: 9ff9ece8a699
Revises: 36d74c0a988b
Create Date: 2025-01-03 14:41:41.196253

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ff9ece8a699"
down_revision = "36d74c0a988b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "permissions_agent_unit_node_uuid_fkey", "permissions", type_="foreignkey"
    )
    op.drop_column("permissions", "agent_unit_node_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions",
        sa.Column(
            "agent_unit_node_uuid", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "permissions_agent_unit_node_uuid_fkey",
        "permissions",
        "units_nodes",
        ["agent_unit_node_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
