"""dashboards

Revision ID: cd843038fae8
Revises: 069d51ae42a8
Create Date: 2025-09-01 00:08:23.909927

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "cd843038fae8"
down_revision = "069d51ae42a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("grafana_uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dashboard_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inc_last_version", sa.Integer(), nullable=True),
        sa.Column("create_datetime", sa.DateTime(), nullable=False),
        sa.Column("creator_uuid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_dashboards_uuid"), "dashboards", ["uuid"], unique=False)
    op.create_table(
        "dashboard_panels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("create_datetime", sa.DateTime(), nullable=False),
        sa.Column("creator_uuid", sa.UUID(), nullable=True),
        sa.Column("dashboard_uuid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dashboard_uuid"], ["dashboards.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_dashboard_panels_uuid"), "dashboard_panels", ["uuid"], unique=False
    )
    op.create_table(
        "mtm_panels_unit_nodes",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("is_last_data", sa.Boolean(), nullable=False),
        sa.Column("create_datetime", sa.DateTime(), nullable=False),
        sa.Column("creator_uuid", sa.UUID(), nullable=True),
        sa.Column("unit_node_uuid", sa.UUID(), nullable=True),
        sa.Column("dashboard_panels_uuid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dashboard_panels_uuid"], ["dashboard_panels.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_node_uuid"], ["units_nodes.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_mtm_panels_unit_nodes_uuid"),
        "mtm_panels_unit_nodes",
        ["uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_mtm_panels_unit_nodes_uuid"), table_name="mtm_panels_unit_nodes"
    )
    op.drop_table("mtm_panels_unit_nodes")
    op.drop_index(op.f("ix_dashboard_panels_uuid"), table_name="dashboard_panels")
    op.drop_table("dashboard_panels")
    op.drop_index(op.f("ix_dashboards_uuid"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
