"""add_force

Revision ID: b552dfb75bb7
Revises: 4ab0c9c39dfc
Create Date: 2025-09-09 00:59:40.577669

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b552dfb75bb7'
down_revision = '4ab0c9c39dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mtm_panels_unit_nodes', sa.Column('is_forced_to_json', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mtm_panels_unit_nodes', 'is_forced_to_json')
    # ### end Alembic commands ###
