"""org_name

Revision ID: 069d51ae42a8
Revises: 934f56855401
Create Date: 2025-08-23 00:51:06.802076

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "069d51ae42a8"
down_revision = "934f56855401"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "grafana_org_name",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "grafana_org_name")
    # ### end Alembic commands ###
