"""user_add_grafana_id

Revision ID: 4ab0c9c39dfc
Revises: 3a47b8943f6f
Create Date: 2025-09-04 00:47:49.859185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4ab0c9c39dfc'
down_revision = '3a47b8943f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grafana_org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grafana_org_id')
    # ### end Alembic commands ###
