"""max_edge_per_node

Revision ID: 99db704045c6
Revises: 5276216fd8d3
Create Date: 2025-11-14 07:21:42.501272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '99db704045c6'
down_revision = '5276216fd8d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units_nodes",
        sa.Column(
            "max_connections", sa.Integer(), nullable=False, server_default="10"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units_nodes", "max_connections")
    # ### end Alembic commands ###
