"""repository_registry

Revision ID: 21a3d2806b9c
Revises: 36edfe9f8fb0
Create Date: 2025-06-27 01:07:05.341627

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "21a3d2806b9c"
down_revision = "36edfe9f8fb0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_registry",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repository_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_public_repository", sa.Boolean(), nullable=False),
        sa.Column("local_repository_size", sa.Integer(), nullable=False),
        sa.Column("sync_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_last_datetime", sa.DateTime(), nullable=True),
        sa.Column("create_datetime", sa.DateTime(), nullable=False),
        sa.Column("last_update_datetime", sa.DateTime(), nullable=False),
        sa.Column("creator_uuid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("repository_url"),
    )
    op.create_index(
        op.f("ix_repository_registry_uuid"),
        "repository_registry",
        ["uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repository_registry_uuid"), table_name="repository_registry")
    op.drop_table("repository_registry")
    # ### end Alembic commands ###
