"""del_double_fld_repos

Revision ID: b4648160f78e
Revises: 30509dc2da85
Create Date: 2025-07-01 00:16:55.227596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b4648160f78e'
down_revision = '30509dc2da85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'releases_data')
    op.drop_column('repos', 'platform')
    op.drop_column('repos', 'repo_url')
    op.drop_column('repos', 'is_public_repository')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('is_public_repository', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('repo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('releases_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
