"""repo_migration_to_registry

Revision ID: 8e1f15b235c8
Revises: b4aada6f12c2
Create Date: 2025-06-27 01:43:13.343879

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e1f15b235c8"
down_revision = "b4aada6f12c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repos", sa.Column("repository_registry_uuid", sa.UUID(), nullable=True)
    )

    op.execute("""
        UPDATE repos r
        SET repository_registry_uuid = rr.uuid
        FROM repository_registry rr
        WHERE r.repo_url = rr.repository_url
    """)

    op.alter_column("repos", "repository_registry_uuid", nullable=False)

    op.create_foreign_key(
        None,
        "repos",
        "repository_registry",
        ["repository_registry_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "repository_registry_creator_uuid_fkey",
        "repository_registry",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "repository_registry",
        "users",
        ["creator_uuid"],
        ["uuid"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repository_registry", type_="foreignkey")
    op.create_foreign_key(
        "repository_registry_creator_uuid_fkey",
        "repository_registry",
        "users",
        ["creator_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "repos", type_="foreignkey")
    op.drop_column("repos", "repository_registry_uuid")
    # ### end Alembic commands ###
