"""data_pipe_init

Revision ID: 36edfe9f8fb0
Revises: c8284720446d
Create Date: 2025-05-15 02:10:08.342476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '36edfe9f8fb0'
down_revision = 'c8284720446d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units_nodes', sa.Column('is_data_pipe_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('units_nodes', sa.Column('data_pipe_yml', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('units_nodes', sa.Column('data_pipe_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('units_nodes', sa.Column('data_pipe_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units_nodes', 'data_pipe_error')
    op.drop_column('units_nodes', 'data_pipe_status')
    op.drop_column('units_nodes', 'data_pipe_yml')
    op.drop_column('units_nodes', 'is_data_pipe_active')
    # ### end Alembic commands ###
