"""releases_to_registry

Revision ID: 30509dc2da85
Revises: 8e1f15b235c8
Create Date: 2025-06-28 11:50:01.898116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30509dc2da85'
down_revision = '8e1f15b235c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_registry', sa.Column('releases_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###

    op.execute(
    """
        UPDATE repository_registry rr
        SET releases_data = r.releases_data
        FROM repos r
        WHERE rr.uuid = r.repository_registry_uuid
        AND r.releases_data IS NOT NULL
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_registry', 'releases_data')
    # ### end Alembic commands ###
