"""dashboards_sync

Revision ID: 3a47b8943f6f
Revises: cd843038fae8
Create Date: 2025-09-02 01:06:43.983104

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "3a47b8943f6f"
down_revision = "cd843038fae8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboards",
        sa.Column("sync_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "dashboards",
        sa.Column("sync_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "dashboards", sa.Column("sync_last_datetime", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboards", "sync_last_datetime")
    op.drop_column("dashboards", "sync_error")
    op.drop_column("dashboards", "sync_status")
    # ### end Alembic commands ###
