"""update_time_node

Revision ID: 199c13471f04
Revises: 9ff9ece8a699
Create Date: 2025-01-25 07:39:24.312206

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '199c13471f04'
down_revision = '9ff9ece8a699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units_nodes', sa.Column('last_update_datetime', sa.DateTime(), nullable=False, server_default='2025-01-25 00:00:00.000000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units_nodes', 'last_update_datetime')
    # ### end Alembic commands ###
