"""alerts

Revision ID: 719a3a7b6de4
Revises: 57b3b29d5dfe
Create Date: 2026-09-30 21:54:26.052971

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '719a3a7b6de4'
down_revision = '57b3b29d5dfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('is_scheduled_alert_enable', sa.Boolean(), nullable=False),
    sa.Column('scheduled_notification_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_data_pipe_alert_enable', sa.Boolean(), nullable=False),
    sa.Column('is_telegram_alert_enable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_index(op.f('ix_notification_settings_uuid'), 'notification_settings', ['uuid'], unique=False)
    op.create_table('notifications',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_datetime', sa.DateTime(), nullable=True),
    sa.Column('target_user_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_notifications_target_user_uuid'), 'notifications', ['target_user_uuid'], unique=False)
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=False)
    # ### end Alembic commands ###

    # Existing users have no settings row. Scheduled and data pipe alerts
    # join this table, so a missing row means those users never receive them.
    # New users get the same defaults in UserService.create.
    op.execute(
        """
        INSERT INTO notification_settings (
            uuid,
            user_uuid,
            is_scheduled_alert_enable,
            scheduled_notification_time,
            is_data_pipe_alert_enable,
            is_telegram_alert_enable
        )
        SELECT gen_random_uuid(), uuid, true, '16:00', true, true
        FROM users
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_user_uuid'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_uuid'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
