"""add_instances

Revision ID: 735532d2f01a
Revises: 99db704045c6
Create Date: 2026-09-03 07:23:22.258052

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '735532d2f01a'
down_revision = '99db704045c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trust_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_ping', sa.Float(), nullable=True),
    sa.Column('last_collection_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_success_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_datetime', sa.DateTime(), nullable=True),
    sa.Column('consecutive_success_count', sa.Integer(), nullable=False),
    sa.Column('last_collection_error', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_instances_uuid'), 'instances', ['uuid'], unique=False)
    op.create_table('operation_tasks',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('finish_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_operation_tasks_uuid'), 'operation_tasks', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_tasks_uuid'), table_name='operation_tasks')
    op.drop_table('operation_tasks')
    op.drop_index(op.f('ix_instances_uuid'), table_name='instances')
    op.drop_table('instances')
    # ### end Alembic commands ###
