"""alerts

Revision ID: a9bb19bc3e98
Revises: 57b3b29d5dfe
Create Date: 2026-10-08 00:11:16.987189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9bb19bc3e98'
down_revision = '57b3b29d5dfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('is_scheduled_alert_enable', sa.Boolean(), nullable=False),
    sa.Column('scheduled_notification_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_data_pipe_alert_enable', sa.Boolean(), nullable=False),
    sa.Column('is_telegram_alert_enable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_index(op.f('ix_notification_settings_uuid'), 'notification_settings', ['uuid'], unique=False)
    op.create_table('notifications',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_datetime', sa.DateTime(), nullable=True),
    sa.Column('small_text', sa.String(length=96), nullable=True),
    sa.Column('table_text', sa.Text(), nullable=True),
    sa.Column('big_text', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_notifications_is_processed'), 'notifications', ['is_processed'], unique=False)
    op.create_index(op.f('ix_notifications_user_uuid'), 'notifications', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=False)
    # ### end Alembic commands ###

    # Users created before this table have no row. Processing joins settings,
    # so a missing row keeps that user's alerts unprocessed forever.
    op.execute(
        """
        INSERT INTO notification_settings (
            uuid,
            user_uuid,
            is_scheduled_alert_enable,
            scheduled_notification_time,
            is_data_pipe_alert_enable,
            is_telegram_alert_enable
        )
        SELECT
            gen_random_uuid(),
            users.uuid,
            true,
            '16:00',
            true,
            true
        FROM users
        WHERE NOT EXISTS (
            SELECT 1
            FROM notification_settings
            WHERE notification_settings.user_uuid = users.uuid
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_processed'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_uuid'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
